mimir-distributed:
  global:
    extraEnvFrom:
    - secretRef:
        name: s3

  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            bucket_name: bc4-mimir-1
            endpoint: ams3.digitaloceanspaces.com
            access_key_id: "${S3_ACCESS_KEY}"
            secret_access_key: "${S3_SECRET_KEY}"
      blocks_storage:
        storage_prefix: blocks
      alertmanager_storage:
        storage_prefix: alertmanager
      ruler_storage:
        storage_prefix: ruler

  runtimeConfig:
    overrides:
      ben:
        max_global_series_per_user: 250000
        ingestion_rate: 20000
        ingestion_burst_size: 200000
        ruler_max_rules_per_rule_group: 50

  alertmanager:
    enabled: false
    replicas: 1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 100Mi
    persistentVolume:
      enabled: true
      size: 1Gi

  compactor:
    replicas: 1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 200Mi
    persistentVolume:
      enabled: true
      size: 5Gi

  distributor:
    replicas: 1
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 500Mi

  gateway:
    enabled: true
    enabledNonEnterprise: true
    replicas: 1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 200Mi

  ingester:
    replicas: 3
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 1000Mi
    persistentVolume:
      enabled: true
      size: 10Gi

  minio:
    enabled: false

  nginx:
    enabled: false

  overrides_exporter:
    enabled: true
    replicas: 1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 100Mi

  querier:
    replicas: 1
    resources:
      requests:
        memory: 300Mi
        cpu: 1000m
      limits:
        memory: 500Mi

  query_frontend:
    replicas: 1
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 300Mi

  query_scheduler:
    enabled: true
    replicas: 1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 100Mi

  ruler:
    enabled: true
    replicas: 1
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 300Mi

  store_gateway:
    replicas: 1
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 300Mi
    persistentVolume:
      enabled: true
      size: 2Gi

  rollout_operator:
    enabled: true

  metaMonitoring:
    dashboards:
      enabled: true
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Mimir Dashboards
      labels:
        grafana_dashboard: "1"
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      mimirAlerts: true
      mimirRules: true
    grafanaAgent:
      enabled: false
