alloy:
  alloy:
    resources:
      requests:
        cpu: 1000m
        memory: 1000Mi
      limits:
        memory: 2000Mi
    stabilityLevel: "generally-available"
    configMap:
      content: |
        prometheus.operator.servicemonitors "default" {
          forward_to = [prometheus.remote_write.mimir.receiver]
          scrape {
            default_scrape_interval = "15s"
          }
        }
        prometheus.operator.podmonitors "default" {
          forward_to = [prometheus.remote_write.mimir.receiver]
          scrape {
            default_scrape_interval = "15s"
          }
        }
        prometheus.operator.probes "default" {
          forward_to = [prometheus.remote_write.mimir.receiver]
          scrape {
            default_scrape_interval = "15s"
          }
        }
        prometheus.remote_write "mimir" {
          endpoint {
            url = "http://mimir-gateway.mimir.svc.cluster.local/api/v1/push"
            headers = {
              "X-Scope-OrgID" = "ben",
            }
          }
        }
        mimir.rules.kubernetes "default" {
          address = "http://mimir-gateway.mimir.svc.cluster.local:80"
          tenant_id = "ben"
        }

  controller:
    type: statefulset
  serviceMonitor:
    enabled: true
