loki-distributed:
  fullnameOverride: loki

  loki:
    storage_config:
      object_prefix: loki
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
      aws:
        endpoint: ams3.digitaloceanspaces.com
        bucketnames: bc4-monitoringdata-1

  compactor:
    extraEnvFrom:
    - secretRef:
        name: s3
  distributor:
    extraEnvFrom:
    - secretRef:
        name: s3
  gateway:
    enabled: true
  ingester:
    extraEnvFrom:
    - secretRef:
        name: s3
  querier:
    extraEnvFrom:
    - secretRef:
        name: s3
  queryFrontend:
    extraEnvFrom:
    - secretRef:
        name: s3
