loki-distributed:
  fullnameOverride: loki

  loki:
    storageConfig:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
      aws:
        endpoint: ams3.digitaloceanspaces.com
        bucketnames: bc4-loki-1
    schemaConfig:
      configs:
      - from: 2024-05-19
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
    structuredConfig:
      auth_enabled: true

  compactor:
    extraEnvFrom:
    - secretRef:
        name: s3
  distributor:
    extraEnvFrom:
    - secretRef:
        name: s3
  gateway:
    enabled: true
  ingester:
    extraEnvFrom:
    - secretRef:
        name: s3
  querier:
    extraEnvFrom:
    - secretRef:
        name: s3
  queryFrontend:
    extraEnvFrom:
    - secretRef:
        name: s3
