grafana:
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    enabled: true
    size: 1Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      external-dns.alpha.kubernetes.io/ttl: "60"
    hosts:
    - grafana.bc4.uk
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.bc4.uk
  admin:
    existingSecret: admin
    userKey: admin-user
    passwordKey: admin-password
  sidecar:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
    dashboards:
      enabled: true
      searchNamespace: ALL
