apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-aws-route53-bc4-uk
  namespace: infra-core
spec:
  encryptedData:
    credentials: AgAlIMNfgFNyTx1b4KtUxMTZDH6Z0eXHzp8wrt5lNEKCzxHyVN9ky+9fo4IzZLvTLgkt82cPF1BdlYId+pBuarkSV1MH6psT0iRXGdHDs0o2jbXrP3ST90X8vYnf1arl8sCrc4qgBnIr6OW5rCpq1nYLr0f2WvZjLdbkqHtP1A5Mb2lvs+deA+bXexwll9YaL01OA97oftFBg8n6WQMMk1ReoW9c8hksyteHngw74Fq7kBsQpDQv6Pemw3aXOygA1GElZFp1BJdGMf1yw5JCqLXSWZ1+vQCQOj5mLxciaiJVfyWt11zl2XNsAkSRWfVidTwUCJoRhx9i3CxlhQahmdfU10+LSMAPQiYaNX9kZQ10sVRxxHwV4zchJO2x1ADaBtpGtX1CQI3Qv7sIfwSVJLKSs8K606q1RdjDUdSmRV71Rz+GVoP9WL6zefyrFBYCeyHH3uNI2j7FUIoCPSVD5OEvPzzEl1BVqdeEeeHhbv0IqClEC7ba1mEYvuLS1JlYI2JhpRDXXJhswfgfgH1d6Tg0zR21du5RLikQSjPw0GQG8x3I4t4PtMqVI8WY2fAAM6PoSPfMAD5Ns7t5dTTy+aGpjpcmGzTAnaPebIamH8P9qzt7ORDUQDbkxNWs+7BorvTDSYbYblz46RsXop3/Fpbimf0nRE49+6s6HnSsJ4WLzMtFjlVhayIUc+k1YxzIBhIbZvHikJRCq75Le1b+vF02EGfjCtBCzEDtPLn9LzHmYMHtvLXOX/sJD8Rq78+u3MTC8SVH2qSHhOzYXpDKxfgi35ZhwdsXvEyBtk3TxI/8XhpbZDxLZ8QPeiph3wDqWjhwzlsB6r8ZUiH0YvUWOfsZ9hQ2cw==
  template:
    metadata:
      name: external-dns-aws-route53-bc4-uk
      namespace: infra-core
    type: Opaque

