apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: webmaster@bc4.uk
    privateKeySecretRef:
      name: acme-letsencrypt-staging
    solvers:
      - selector: {}
        dns01:
          route53:
            region: eu-west-2
            accessKeyID: AKIAX6IW6HTOAN4J25OB
            secretAccessKeySecretRef:
              name: route53
              key: secret-access-key
