apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-all-http-to-https-by-default
  namespace: infrastructure
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      priority: 1
      middlewares:
        - name: redirect-http-to-https
