external-dns:
  provider: aws
  policy: sync
  registry: txt
  txtOwnerId: external-dns
  domainFilters:
    - bc4.uk
  sources:
    - service
    - ingress
  extraArgs:
    - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
  env:
    - name: AWS_DEFAULT_REGION
      value: eu-west-2
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: /.aws/credentials
  extraVolumes:
    - name: aws-credentials
      secret:
        secretName: external-dns-aws-route53-bc4-uk
  extraVolumeMounts:
    - name: aws-credentials
      mountPath: /.aws
      readOnly: true
