opentelemetry-demo:
  default:
    envOverrides:
    - name: OTEL_COLLECTOR_NAME
      value: alloy.alloy.svc.cluster.local
  grafana:
    enabled: false
  opentelemetry-collector:
    enabled: false
  jaeger:
    enabled: false
  prometheus:
    enabled: false
