tempo-distributed:
  global:
    extraEnvFrom:
    - secretRef:
        name: s3
  storage:
    trace:
      backend: s3
      s3:
        bucket_name: bc4-monitoringdata-1
        endpoint: ams3.digitaloceanspaces.com
        access_key: "${S3_ACCESS_KEY}"
        secret_key: "${S3_SECRET_KEY}"
        prefix: tempo
  minio:
    enabled: false
  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
    zipkin:
      enabled: false
    jaeger:
      thriftHttp:
        enabled: false
    opencensus:
      enabled: false
  metaMonitoring:
    serviceMonitor:
      enabled: true
